# Generated by Django 5.0.6 on 2024-06-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='imgenBeat',
            field=models.ImageField(blank=True, null=True, upload_to='Beats/'),
        ),
        migrations.AddField(
            model_name='beat',
            name='precioBeat',
            field=models.IntegerField(default=50, verbose_name='Precio Beat'),
            preserve_default=False,
        ),
    ]
