# Generated by Django 5.0.6 on 2024-06-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_beat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='user',
        ),
    ]
